name: CI

on: push

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache dependencies ⚡
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies 🔧
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Lint ✅
        run: cd backend && npm run lint

      - name: Build 🏗️
        run: cd backend && npm run build && cd frontend && npm run build
